### ISSUE TITLE
Upgrade Node version

### ISSUE THREAD

**Issue by craig95** [Inrixia/Secret-Injector#2]
GitHub Actions is now using Node v16 by default. 
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

This action fails to run on Node v16.

**Comment by Inrixia** [comment]
Should be an easy update. I'll try get to it in the next few days. Feel free to open a pr if you need it sooner

**Comment by Inrixia** [comment]
This should work fine on 16 now. Let me know if its still not working
